### ISSUE TITLE
please Add support for 12.5

### ISSUE THREAD

**Issue by mohamedsaqer** [iGhibli/iOS-DeviceSupport#136]

**Comment by codeskyblue** [comment]
Only see directory under `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/`

```
9.0
9.1
9.2
9.3
10.0
10.1
10.2
10.3
11.0
11.1
11.2
11.3
11.4
12.0
12.1
12.2
12.3
12.4
13.0
13.1
13.2
13.3
13.4
13.5
13.6
13.7
14.0
```

no 12.5 found

**Comment by codeskyblue** [comment]
I tested, 12.4 DeveloperImage can mounted to 12.5 iOS system

**Comment by jeanthom** [comment]
Tested renaming iOS 12.4 to 12.5 on XCode 9.4.1/macOS High Sierra, it also works

**Comment by mreis1** [comment]
How's it possible that there's no iOS simulator for iOS 12.5? There has to be a difference between iOS 12.4 and and iOS 12.5 runtime so there should be a simulator for that.
 
I tried running my app on iOS 12.4 and it didn't crash but many of my iOS 12.5 customers are getting app crashes while the app is booting. 

![image](https://user-images.githubusercontent.com/1719667/190670235-6c143cd2-d91e-4eb3-b547-54c556fecbbd.png)

>  Tested renaming iOS 12.4 to 12.5 on XCode 9.4.1/macOS High Sierra, it also works
Renaming 12.4 in 12.5 makes no sense to me, because we'll be testing our app in a 12.4 runtime. Not in 12.5.
